using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using System.IO;
using System;
using System.Linq;

public class GetCharacters : MonoBehaviour
{
    [Header("A Whole Bunch Of Lists")]

    public string[] allPaths;
    public List<string> paths;
    //public List<string> words;
    public List<TextAsset> characterFiles;

    [Header("Controls")]
    public bool getFiles;
    public bool getCharacters;
    public bool getInfo;
    public bool getDialog;
    public bool getQuestions;
    public bool getAnswers;
    public bool getStatusUpdates;
    public bool debug;

    [Header("Final CHaracters List")]

    public List<Character> characters = new List<Character>();




    // Use this for initialization
    void Start()
    {

        //Gets the character.txt files.
        if (getFiles)
            GetFiles();


        //Start of the descipherer.
        if (getFiles)
            GetCharacter();


    }

    public void GetFiles()
    {
        paths.Clear();
        allPaths = Directory.GetFiles(Application.dataPath, "*", SearchOption.AllDirectories); //ALL the files in the assets folder.

        foreach (string p in allPaths)
        {
            if (p.Contains("Character_") && !p.Contains("meta")) //Narrows down ALL the files to only the Character.txt files.
            {
                paths.Add(p);
                print(p);
            }
        }
    }

    public void GetCharacter()
    {
        for (int c = 0; c < paths.Count; c++) //Amount of paths = amount of files found = amount of characters.
        {
            print("_________________________________________________________________________________________________");
            print("Start of Loop: " + c);

            //Gets the file names from the paths and reformats them to be readable by Resource.Load.
            string output = paths[c].Substring(paths[c].IndexOf(',') + 1); //to get a 'Characters/Characters.txt path' (to be ready by Resoures.Load) I placed a ',' (not used in any other path).
            print(output);
            output = output.Substring(0, output.Length - 4); //Removes '.txt'
            //print(output);

            characterFiles.Add((TextAsset)Resources.Load("," + output, typeof(TextAsset))); //Takes the paths generated by 'output' and gets the Character.txt files.

            characters.Add(new Character()); //For each Characters.txt file found make a new entry in the list.
            string[] splitString = characterFiles[c].text.Split(new string[] { "\n" }, StringSplitOptions.None); //Get each seperate line from the Characters.txt files.
            print("Amount of lines in " + characterFiles[c].name + "'s file: " + splitString.Length.ToString());


            for (int s = 0; s < splitString.Length; s++) // 's' = amount of sentences.
            {
                //print("Line " + s + ": " + splitString[s]);
                Debug("Line " + s + ": " + splitString[s]);
                ;
                //This box gets all the info per line. Might change later.


                if (getInfo && splitString[s].Contains("[Info]"))
                {
                    Debug("Found [Info] for: " + splitString[s + 1]);
                    Level1Debug("Found name: " + splitString[s + 1]);
                    characters[c].name = splitString[s + 1];
                    Level2Debug("Name for Character " + c + " (" + characters[c].name + ") " + "is now: " + characters[c].name);
                    Level1Debug("Found value: " + splitString[s + 2]);
                    characters[c].value = splitString[s + 2];
                    Level2Debug("Value for Character " + c + " (" + characters[c].name + ") " + "is now: " + characters[c].value);
                    Level1Debug("Found info: " + splitString[s + 3]);
                    characters[c].info = splitString[s + 3];
                    Level2Debug("Info for Character " + c + " (" + characters[c].name + ") " + "is now: " + characters[c].info);

                }

                //Here come the dialog.

                if (getDialog && splitString[s].Contains("[Dialog]"))
                {
                    Debug("Found [Dialog] for: " + characters[c].name);

                    for (int r = 0; r < splitString.Length; r++)
                    {
                        for (int q = 0; q < 20; q++) //Amount of questions to check.
                        {
                            if (splitString[r].Contains("Q" + q.ToString()))
                            {
                                Level2Debug("Adding question '" + splitString[r] + "' to " + characters[c].name);
                                characters[c].questions.Add(new Question(splitString[r], false)); //Adds a question to the list with the string d and a 'answered' value of false. So, an unaswered question.
                                Level2Debug("Added question '" + splitString[r] + "' to " + characters[c].name);
                                for (int a = 1; a < 10; a++) //Amount of answers to check.
                                {

                                    //print("------ Checking for answer with " + "A" + q.ToString() + "." + a.ToString() + " on line " + (r + a).ToString());
                                    if (splitString.Length > (r + a))
                                    {
                                        if (splitString[r + a].Contains("A" + q.ToString() + "." + a.ToString()))
                                        {
                                            Level3Debug("Found answer '" + splitString[r + a] + "' to " + characters[c].name + " on line " + (r + a).ToString());
                                            Level3Debug("Adding answer '" + splitString[r + a] + "' to " + characters[c].name + " to question " + (q - 1));
                                            //characters[c].questions[q].answers.Add(new Answer());

                                            characters[c].questions[q - 1].answers.Add(new Answer(splitString[r + a], 0));
                                            Level3Debug("Added answer '" + splitString[r + a] + "' to " + characters[c].name);


                                        }
                                        else {
                                            Level3Debug("No answer found.");

                                        }
                                    }
                                    else {
                                        //print("--------- Past end of file.");
                                    }
                                }

                            }
                        }


                    }
                }
            }
        }
    }
    public void Debug(string message)
    {
        if (debug)
            print(message);
    }

    public void Level1Debug(string message)
    {
        if (debug)
            print("|--- " + message);
    }

    public void Level2Debug(string message)
    {
        if (debug)
            print("    |--- " + message);
    }

    public void Level3Debug(string message)
    {
        if (debug)
            print("        |--- " + message);
    }



}